name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1
        with:
          java-version: 17
          maven-version: 3.9.4
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
